### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by digitall-it** [wernerkrauss/silverstripe-onepage#11]
It would be nice to see what does this module produce on the frontend.

**Comment by wernerkrauss** [comment]
There are some sites out that use this module, e.g.

http://www.hallstattmarketing.at/
http://www.seerundlauf.hallstatt.net/

and of course my own site http://www.netwerkstatt.at/ ;)

The module provides some basic stuff and you still need a lot of customisation. It's no ready-to-use template (though this would be an intersting idea...?)

**Comment by digitall-it** [comment]
Nice usage, would add them to the README as example. It is understandable that this is not a ready-to-use template. Any example template should be provided in another module in my opinion.

Could this be integrated in a normal multipage site to produce an isolated landing page?

**Comment by wernerkrauss** [comment]
Of course. It's just "yet another page type" you can use side by side with your current installation. But maybe another of the many block modules fits better for your needs... There are some out there.

**Comment by digitall-it** [comment]
Yes but this is specially tailored to produce a one page site with stellar and in-page navigation already built in, so it fills some nice use cases as a landing page generator. Just add some HTML and it's almost a turnkey solution to have an entirely different landing page inside your site.
