### ISSUE TITLE
Problems with colorpalette

### ISSUE THREAD

**Issue by mckdesign** [wernerkrauss/silverstripe-onepage#12]
The installation, using composer, fails:
Problem 1
    - Installation request for wernerkrauss/silverstripe-onepage dev-master -> satisfiable by wernerkrauss/silverstripe-onepage[dev-master].
    - wernerkrauss/silverstripe-onepage dev-master requires heyday/silverstripe-colorpalette dev-master -> satisfiable by heyday/silverstripe-colorpalette[dev-master] but these conflict with your requirements or minimum-stability.

Secondly, upon manual install of colorpalette, I get the radio boxes for colours but not the colour palette boxes themselves:
<img width="745" alt="screen shot 2017-11-03 at 9 48 59 am" src="https://user-images.githubusercontent.com/16911086/32349571-5f31cf9c-c07c-11e7-823d-d722cac623e9.png">

**Comment by wernerkrauss** [comment]
Which version of SilverStripe are you using? Also did you try to install a tagged version, e.g. https://packagist.org/packages/wernerkrauss/silverstripe-onepage#0.3.1 ?

**Comment by mckdesign** [comment]
Had colorpalette module in wrong place as I had to manually install and dragged inside the onepage directory as opposed to top level. However, composer issue still exists which is why I got into trouble in the first place.
