### ISSUE TITLE
All pages outside of OnePageHolder have layout tab

### ISSUE THREAD

**Issue by helenclarko** [wernerkrauss/silverstripe-onepage#3]
The layout tab has been added to all pages regardless of whether they are a child of OnePageHolder.

layout has colourpalette which is a requirement, so in order to submit pages outside of OnePageHolder you need to pick a colour in the layout tab.

Is there anyway to only have the layout tab on children of OnePageHolder?

**Comment by wernerkrauss** [comment]
Hi Helen,

thanks for the feedback! Good to know my module is used by someone else than me ;)

In my previous projects i also needed colors and other fields for the OnePageHolder, so it was no problem for me.

I stumbled over this in my last project but didn't need the Layout tab at whole (just the onepage logic), so i hacked it away in my Page class:

```
    public function getCMSFields() {
        $fields = parent::getCMSFields();

        /**
         * disable fields added by onepage module
         */
        $fields->removeFieldFromTab('Root', 'Layout');

        return $fields;
    }
```

I fixed your issues in 0.1.2, you have to adjust the newly added config vars to limit the Layout tab to slides only and/or accept emtpy colors.
