### ISSUE TITLE
Onepage translatable problem

### ISSUE THREAD

**Issue by kabutzel** [wernerkrauss/silverstripe-onepage#9]
I am using the module together with the translatable module. When attaching a subpage to a onepageholder page, the focus switches from the subpage back to the holder page, so that it´s impossible to add or change content of the childpage.

**Comment by wernerkrauss** [comment]
That's true, for a simple workaround: go to "edit" view, no split view. I have to implement a check for redirecting a slide only for frontend

**Comment by kabutzel** [comment]
Ok, thank you!!

**Comment by wernerkrauss** [comment]
Does it work now? That was quite a task, thanks to @kinglozzer for giving me the hints how that preview stuff works in LeftAndMain
